### ISSUE TITLE
Using the Plugin in NativeScript + Vue

### ISSUE THREAD

**Issue by ghost** [VedantMistry13/nativescript-media-metadata-retriever#4]
I would like to keep my app out of Angular right now, is it possible to use this plugin even in pure Vue.js + NativeScript projects too?

**Comment by VedantMistry13** [comment]
Hi @szhatef ,
I have not updated the plugin for a long time but, as fas as my knowledge of nativescript go, I believe NativeScript provides access to Android and iOS APIs. So you can use these APIs directly. You can use the methods created in this file [media-metadata-retriever.android.ts](https://github.com/VedantMistry13/nativescript-media-metadata-retriever/blob/master/media-metadata-retriever.android.ts) to make your own functions.
